document.writeln("<form class=\"send\" id=\"Inquiry\" name=\"Inquiry\" method=\"post\" action=\"https://q.kssbchina.com/information/\"");
document.writeln("          onsubmit=\"return doSubmits()\">");
document.writeln("          <div class=\"input-panel clearfix\">");
document.writeln("            <div class=\"me one\">");
document.writeln("              <input id=\"productname\" name=\"productname\" class=\"txt icon-text-pro\" placeholder=\"название\"");
document.writeln("                type=\"text\">");
document.writeln("            </div>");
document.writeln("            <div class=\"me two\">");
document.writeln("              <input id=\"name\" name=\"name\" class=\"txt icon-text-user\" placeholder=\"ваше имя\" type=\"text\">");
document.writeln("            </div>");
document.writeln("            <div class=\"me three\">");
document.writeln("              <input id=\"email\" name=\"email\" class=\"txt icon-text-email\" placeholder=\"Ваш адрес электронной почты(*)\" type=\"text\">");
document.writeln("            </div>");
document.writeln("            <div class=\"me four\">");
document.writeln("              <input id=\"telephone\" name=\"telephone\" class=\"txt icon-text-tel\" placeholder=\"Ваш телефон\"");
document.writeln("                type=\"text\">");
document.writeln("            </div>");
document.writeln("          </div>");
document.writeln("          <div class=\"me five\">");
document.writeln("            <textarea id=\"message\" class=\"textarea icon-text-message\" name=\"message\"");
document.writeln("              placeholder=\"Название оборудования, модель, сопутствующие вопросы(*)\"></textarea>");
document.writeln("          </div>");
document.writeln("          <input id=\"site_feedback\" type=\"hidden\" name=\"site_feedback\">");
document.writeln("          <input id=\"from_way\" type=\"hidden\" name=\"from_way\">");
document.writeln("          <input id=\"refer\" type=\"hidden\" name=\"refer\">");
document.writeln("          <div class=\"PorConSixXX\">");
document.writeln("            <p><input type=\"checkbox\" class=\"choose_input\"></p>Я принимаю Заявление о защите данных");
document.writeln("          </div>");
document.writeln("          <input id=\"button_sub\" class=\"btn-primary\" type=\"submit\"");
document.writeln("            onclick=\"_czc.push([\'_trackEvent\',window.location.host, \'liuyan\' , \'0\' , \'\' ]);\" value=\"немедленная отправка!\">");
document.writeln("        </form>");

//document.writeln(" <form id=\"Inquiry\" name=\"Inquiry\" class=\"send clearfix\" method=\"post\" action=\"https://q.kssbchina.com/information/\"");
//document.writeln("                        onsubmit=\"return doSubmits()\">");
//document.writeln("                        <div class=\"input-panel clearfix\">");
//document.writeln("                            <div class=\"me one\">");
//document.writeln("                                <strong>название: </strong>");
//document.writeln("                                <input id=\"productname\" name=\"productname\" class=\"txt icon-text-pro\"");
//document.writeln("                                    placeholder=\"название\" type=\"text\">");
//document.writeln("                            </div>");
//document.writeln("                            <div class=\"me two\">");
//document.writeln("                                <strong>ваше имя:</strong>");
//document.writeln("                                <input id=\"name\" name=\"name\" class=\"txt icon-text-user\" placeholder=\"ваше имя\"");
//document.writeln("                                    type=\"text\">");
//document.writeln("                            </div>");
//document.writeln("                            <div class=\"me three\">");
//document.writeln("                                <strong>Ваш адрес электронной почты(<span style=\"margin: 0px; color: red\">*</span>)</strong>");
//document.writeln("                                <input id=\"email\" name=\"email\" class=\"txt icon-text-email\" placeholder=\"Ваш адрес электронной почты\"");
//document.writeln("                                    type=\"text\">");
//document.writeln("                            </div>");
//document.writeln("                            <div class=\"me four\">");
//document.writeln("                                <strong>Ваш телефон или WhatsApp:</strong>");
//document.writeln("                                <input id=\"telephone\" name=\"telephone\" class=\"txt icon-text-tel\"");
//document.writeln("                                    placeholder=\"Ваш телефон или WhatsApp\" type=\"text\">");
//document.writeln("                            </div>");
//document.writeln("                        </div>");
//document.writeln("                        <div class=\"me five clearfix\">");
//document.writeln("                            <strong>Сообщение(<span style=\"margin: 0px; color: red\"> как можно конкретнее*</span>)</strong>");
//document.writeln("                            <textarea id=\"message\" class=\"textarea icon-text-message\" name=\"message\"");
//document.writeln("                                placeholder=\"Название оборудования, модель, сопутствующие вопросы\"></textarea>");
//document.writeln("                        </div>");
//document.writeln("                        <input id=\"site_feedback\" type=\"hidden\" name=\"site_feedback\">");
//document.writeln("                        <input id=\"from_way\" type=\"hidden\" name=\"from_way\">");
//document.writeln("                        <input id=\"refer\" type=\"hidden\" name=\"refer\">");
//document.writeln("                        <div class=\"PorConSixXX\">");
//document.writeln("                            <p><input type=\"checkbox\" class=\"choose_input\"><label></label></p>Я принимаю Заявление о защите данных");
//document.writeln("                        </div>");
//document.writeln("                        <input id=\"button_sub\" class=\"btn-primary\" type=\"submit\"");
//document.writeln("                            onclick=\"_czc.push([\'_trackEvent\',window.location.host, \'liuyan\' , \'0\' , \'\' ]);\"");
//document.writeln("                            value=\"Отправить сейчас!\">");
//document.writeln("                    </form>");