document.writeln(" <div class=\"message-conter margin-top padding-top\">");
document.writeln("    <div class=\"container\">");
document.writeln("      <div class=\"msg-from clearfix\">");
document.writeln("        <strong>Online Message</strong>");
document.writeln("        <p>Want a senior engineer to design a production plan for you? Want to get a full set of equipment discount quotations? Please leave a message, and the professional manager will start to serve you one to one immediately!</p>");
document.writeln("        <script src=\'/js/liuyan.js?v=12\'></script><script src = \'/js/jsliuyantest.js?v=12\'></script>");
document.writeln("      </div>");
document.writeln("      <div class=\"msg-text\">");
document.writeln("        <strong>Service Process</strong>");
document.writeln("        <ul class=\"clearfix\">");
document.writeln("          <li>");
document.writeln("            <span class=\"img\"><img src=\"/images/profiveicon06.png\" alt=\"\"></span>");
document.writeln("            <h4>Customized Solutions</h4>");
document.writeln("            <p>Visit the factory to get a senior engineer to design a plan for you</p>");
document.writeln("          </li>");
document.writeln("          <li><span class=\"img\"><img src=\"/images/profiveicon07.png\" alt=\"\"></span><h4>Fast delivery</h4><p>Multiple models can be tested in stock, signed a contract, and shipped within 2 days</p></li>");
document.writeln("          <li><span class=\"img\"><img src=\"/images/profiveicon08.png\" alt=\"\"></span><h4>Debug production</h4><p>>The after-sales team guides the equipment installation and commissioning on site, and completes the delivery</p></li>");
document.writeln("          <li><span class=\"img\"><img src=\"/images/profiveicon09.png\" alt=\"\"></span><h4>gained profit</h4><p>Provide production and operation guidance to ensure rapid profitability of the sand plant</p></li>");
document.writeln("        </ul>");
document.writeln("      </div>");
document.writeln("    </div>");
document.writeln("  </div>");